### ISSUE TITLE
您好，我想下载指定搜索的结果

### ISSUE THREAD

**Issue by weidongzhou1994** [Billy-FIN/NMPA_Scraper#2]
如题，NMPA_search_results_by_requests.py 会下载对应数据库下面的所有公司的数据，但是我想只下载指定公司的数据，这个需要在接口里面填写哪个参数？

**Comment by Billy-FIN** [comment]
不好意思。发现你已经关闭这个issue了，还需要帮助吗？

**Comment by weidongzhou1994** [comment]
还需要，这个是在请求里面加哪个参数？还是说是一个新的请求接口

**Comment by Billy-FIN** [comment]
在主程序里，创建spider的时候需要两个参数，其中第二个参数相当于你在搜索框里输入的东西。我是这么想的，你可以把第二个参数设置为你需要的的公司名称，这样查询出来的结果都是该公司的数据了。我预先设置的参数是“经营”，是因为所有”医疗器械经营企业（许可）“数据库里的每一条数据的许可证编号都有“经营”的字样，所以能全部查出来。你可以根据需求自定义探索一下试试

**Comment by Billy-FIN** [comment]
你好，还有需要帮助嘛？我将在后天关闭这个issue。
